/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CourseId = IDL.Text;
export const LessonId = IDL.Text;
export const ProjectId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Lesson = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'courseId' : CourseId,
});
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'instructorName' : IDL.Text,
});
export const TemplateType = IDL.Variant({
  'ad' : IDL.Null,
  'thumbnail' : IDL.Null,
  'blank' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Project = IDL.Record({
  'id' : ProjectId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'videoFile' : IDL.Opt(ExternalBlob),
  'templateType' : TemplateType,
  'updatedAt' : Timestamp,
});
export const LessonProgress = IDL.Record({
  'lessonId' : LessonId,
  'completedAt' : IDL.Opt(Timestamp),
  'userId' : IDL.Text,
});
export const ContactMessageId = IDL.Text;
export const ContactMessage = IDL.Record({
  'id' : ContactMessageId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addLesson' : IDL.Func(
      [CourseId, LessonId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'attachVideoFile' : IDL.Func([ProjectId, ExternalBlob], [IDL.Bool], []),
  'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Course], []),
  'createProject' : IDL.Func([IDL.Text, TemplateType], [Project], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getLessonProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LessonProgress)],
      ['query'],
    ),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'markLessonComplete' : IDL.Func([LessonId, IDL.Text], [IDL.Bool], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CourseId = IDL.Text;
  const LessonId = IDL.Text;
  const ProjectId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Lesson = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'courseId' : CourseId,
  });
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'instructorName' : IDL.Text,
  });
  const TemplateType = IDL.Variant({
    'ad' : IDL.Null,
    'thumbnail' : IDL.Null,
    'blank' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Project = IDL.Record({
    'id' : ProjectId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'videoFile' : IDL.Opt(ExternalBlob),
    'templateType' : TemplateType,
    'updatedAt' : Timestamp,
  });
  const LessonProgress = IDL.Record({
    'lessonId' : LessonId,
    'completedAt' : IDL.Opt(Timestamp),
    'userId' : IDL.Text,
  });
  const ContactMessageId = IDL.Text;
  const ContactMessage = IDL.Record({
    'id' : ContactMessageId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addLesson' : IDL.Func(
        [CourseId, LessonId, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'attachVideoFile' : IDL.Func([ProjectId, ExternalBlob], [IDL.Bool], []),
    'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Course], []),
    'createProject' : IDL.Func([IDL.Text, TemplateType], [Project], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getLessonProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LessonProgress)],
        ['query'],
      ),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'markLessonComplete' : IDL.Func([LessonId, IDL.Text], [IDL.Bool], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };