/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : ContactMessageId,
  'name' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export type ContactMessageId = string;
export interface Course {
  'id' : CourseId,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
  'instructorName' : string,
}
export type CourseId = string;
export type ExternalBlob = Uint8Array;
export interface Lesson {
  'id' : LessonId,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'durationMinutes' : bigint,
  'videoUrl' : string,
  'courseId' : CourseId,
}
export type LessonId = string;
export interface LessonProgress {
  'lessonId' : LessonId,
  'completedAt' : [] | [Timestamp],
  'userId' : string,
}
export interface Project {
  'id' : ProjectId,
  'name' : string,
  'createdAt' : Timestamp,
  'videoFile' : [] | [ExternalBlob],
  'templateType' : TemplateType,
  'updatedAt' : Timestamp,
}
export type ProjectId = string;
export type TemplateType = { 'ad' : null } |
  { 'thumbnail' : null } |
  { 'blank' : null };
export type Timestamp = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addLesson' : ActorMethod<
    [CourseId, LessonId, string, string, string, bigint, bigint],
    boolean
  >,
  'attachVideoFile' : ActorMethod<[ProjectId, ExternalBlob], boolean>,
  'createCourse' : ActorMethod<[string, string, string], Course>,
  'createProject' : ActorMethod<[string, TemplateType], Project>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getLessonProgress' : ActorMethod<[string], Array<LessonProgress>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'markLessonComplete' : ActorMethod<[LessonId, string], boolean>,
  'submitContact' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];