import type {
  CanvasPreset,
  ColorPalette,
  GradientPreset,
  RecentProject,
  ShapePreset,
  Template,
  TemplateElement,
  TextPreset,
  WorkspacePreset,
} from "@/types/editor";
export const CANVAS_PRESETS: CanvasPreset[] = [
  {
    label: "YouTube Thumbnail",
    category: "Video",
    width: 1280,
    height: 720,
    icon: "▶",
  },
  {
    label: "Instagram Post",
    category: "Social",
    width: 1080,
    height: 1080,
    icon: "📷",
  },
  {
    label: "Twitter Banner",
    category: "Social",
    width: 1500,
    height: 500,
    icon: "🐦",
  },
  {
    label: "TikTok Video",
    category: "Video",
    width: 1080,
    height: 1920,
    icon: "🎵",
  },
  {
    label: "LinkedIn Banner",
    category: "Social",
    width: 1200,
    height: 628,
    icon: "💼",
  },
];

// ─── Text Presets (Canva-style) ─────────────────────────────────────────────

export const TEXT_PRESETS: TextPreset[] = [
  {
    name: "Add a heading",
    fontSize: 60,
    fontWeight: "bold",
    fontFamily: "Inter",
    color: "#ffffff",
  },
  {
    name: "Add a subheading",
    fontSize: 36,
    fontWeight: "600",
    fontFamily: "Inter",
    color: "#e2e8f0",
  },
  {
    name: "Add a little bit of body text",
    fontSize: 18,
    fontWeight: "400",
    fontFamily: "Inter",
    color: "#94a3b8",
  },
  {
    name: "Display — extra large",
    fontSize: 80,
    fontWeight: "bold",
    fontFamily: "Impact",
    color: "#ffffff",
  },
  {
    name: "Caption — small label",
    fontSize: 14,
    fontWeight: "400",
    fontFamily: "Inter",
    color: "#94a3b8",
  },
  {
    name: "Highlight — cobalt accent",
    fontSize: 32,
    fontWeight: "bold",
    fontFamily: "Plus Jakarta Sans",
    color: "#0047ab",
  },
  {
    name: "Quote — elegant italic",
    fontSize: 24,
    fontWeight: "400",
    fontFamily: "Georgia",
    color: "#e2e8f0",
  },
  {
    name: "CTA — uppercase bold",
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "Inter",
    color: "#ffffff",
  },
];

// ─── Gradient Presets ────────────────────────────────────────────────────────

export const GRADIENT_PRESETS: GradientPreset[] = [
  { name: "Sunset", colors: ["#ff6b6b", "#feca57"], angle: 135 },
  { name: "Ocean", colors: ["#0047ab", "#50c878"], angle: 135 },
  { name: "Purple Rain", colors: ["#6c5ce7", "#fd79a8"], angle: 135 },
  { name: "Midnight", colors: ["#101820", "#1a2744"], angle: 180 },
  { name: "Gold", colors: ["#f7971e", "#ffd200"], angle: 90 },
  { name: "Neon", colors: ["#00ff00", "#0047ab"], angle: 135 },
  { name: "Rose", colors: ["#ff9a9e", "#fecfef"], angle: 135 },
  { name: "Arctic", colors: ["#a1c4fd", "#c2e9fb"], angle: 135 },
  { name: "Emerald Dream", colors: ["#0d9488", "#50c878"], angle: 135 },
  { name: "Fire", colors: ["#f97316", "#dc2626"], angle: 135 },
  { name: "Candy", colors: ["#ec4899", "#a855f7"], angle: 135 },
  { name: "Forest", colors: ["#14532d", "#00ff00"], angle: 135 },
  { name: "Sky", colors: ["#7dd3fc", "#f0f9ff"], angle: 180 },
  { name: "Lava", colors: ["#dc2626", "#450a0a"], angle: 135 },
  { name: "Citrus", colors: ["#facc15", "#f97316"], angle: 90 },
  { name: "Twilight", colors: ["#1e3a5f", "#7c3aed"], angle: 135 },
];

// ─── Shape Presets ───────────────────────────────────────────────────────────

export const SHAPE_PRESETS: ShapePreset[] = [
  { label: "Rectangle", type: "rect", icon: "▭" },
  { label: "Circle", type: "circle", icon: "○" },
  { label: "Triangle", type: "triangle", icon: "△" },
  { label: "Star", type: "star", icon: "★" },
];

// ─── Brand Colors ────────────────────────────────────────────────────────────

export const BRAND_COLORS: { name: string; hex: string }[] = [
  { name: "Cobalt", hex: "#0047ab" },
  { name: "Emerald", hex: "#50c878" },
  { name: "Matte Black", hex: "#101820" },
  { name: "White", hex: "#ffffff" },
  { name: "Burnt Copper", hex: "#7c4d00" },
  { name: "Cyber Lime", hex: "#00ff00" },
];

export const FONT_FAMILIES = [
  "Inter",
  "Poppins",
  "Bebas Neue",
  "Anton",
  "Montserrat",
  "Oswald",
  "Plus Jakarta Sans",
  "Arial",
  "Impact",
  "Georgia",
  "Courier New",
];

// ─── Sidebar Sections ────────────────────────────────────────────────────────

export const SIDEBAR_SECTIONS = [
  {
    id: "templates",
    label: "Templates",
    icon: "LayoutTemplate",
    tooltip: "Browse templates",
  },
  {
    id: "uploads",
    label: "Uploads",
    icon: "Upload",
    tooltip: "Upload your media",
  },
  { id: "text", label: "Text", icon: "Type", tooltip: "Add text elements" },
  {
    id: "elements",
    label: "Elements",
    icon: "Shapes",
    tooltip: "Shapes & icons",
  },
  {
    id: "images",
    label: "Images",
    icon: "Image",
    tooltip: "Stock image library",
  },
  {
    id: "backgrounds",
    label: "Backgrounds",
    icon: "PaintBucket",
    tooltip: "Background styles",
  },
  { id: "brand", label: "Brand", icon: "Palette", tooltip: "Brand kit" },
  {
    id: "ai-tools",
    label: "AI Tools",
    icon: "Sparkles",
    tooltip: "AI-powered design tools",
  },
  {
    id: "layers",
    label: "Layers",
    icon: "Layers",
    tooltip: "Layer management",
  },
  {
    id: "settings",
    label: "Settings",
    icon: "Settings",
    tooltip: "Canvas settings",
  },
] as const;

// ─── Color Palettes ───────────────────────────────────────────────────────────

export const COLOR_PALETTES: ColorPalette[] = [
  {
    name: "Neon",
    colors: [
      "#00ff00",
      "#00ffff",
      "#ff00ff",
      "#ffff00",
      "#ff0080",
      "#8000ff",
      "#00ff80",
      "#ff8000",
    ],
  },
  {
    name: "Luxury",
    colors: [
      "#d4af37",
      "#b8860b",
      "#c0a060",
      "#1a1a2e",
      "#16213e",
      "#0f3460",
      "#e94560",
      "#f5f5f5",
    ],
  },
  {
    name: "Gaming",
    colors: [
      "#ff4655",
      "#1a1a2e",
      "#00b4d8",
      "#90e0ef",
      "#caf0f8",
      "#7209b7",
      "#f72585",
      "#4cc9f0",
    ],
  },
  {
    name: "YouTube",
    colors: [
      "#ff0000",
      "#282828",
      "#ffffff",
      "#aaaaaa",
      "#606060",
      "#065fd4",
      "#00b894",
      "#fdcb6e",
    ],
  },
  {
    name: "Cyberpunk",
    colors: [
      "#00f5ff",
      "#ff00aa",
      "#fbff00",
      "#0d0d0d",
      "#1a1a2e",
      "#ff6b35",
      "#9d4edd",
      "#2d6a4f",
    ],
  },
  {
    name: "Pastel",
    colors: [
      "#ffb3c1",
      "#ffc8a2",
      "#d4f1c0",
      "#c0e8ff",
      "#e0c8ff",
      "#fff3b0",
      "#b5ead7",
      "#ffdac1",
    ],
  },
  {
    name: "Minimal",
    colors: [
      "#000000",
      "#1a1a1a",
      "#333333",
      "#666666",
      "#999999",
      "#cccccc",
      "#f5f5f5",
      "#ffffff",
    ],
  },
  {
    name: "Retro",
    colors: [
      "#e63946",
      "#457b9d",
      "#1d3557",
      "#f1faee",
      "#a8dadc",
      "#e9c46a",
      "#f4a261",
      "#264653",
    ],
  },
];

// ─── Element Categories ───────────────────────────────────────────────────────

export const ELEMENT_CATEGORIES = [
  {
    id: "shapes",
    label: "Shapes",
    icon: "Shapes",
    items: [
      "rect",
      "circle",
      "triangle",
      "star",
      "pentagon",
      "hexagon",
      "diamond",
      "arrow",
    ],
  },
  {
    id: "arrows",
    label: "Arrows",
    icon: "ArrowRight",
    items: [
      "arrow-right",
      "arrow-left",
      "arrow-up",
      "arrow-down",
      "arrow-double",
      "arrow-curved",
      "arrow-circular",
      "chevron",
    ],
  },
  {
    id: "icons",
    label: "Icons",
    icon: "Smile",
    items: ["star", "heart", "check", "x", "plus", "minus", "search", "bell"],
  },
  {
    id: "gradients",
    label: "Gradients",
    icon: "Layers",
    items: [
      "linear",
      "radial",
      "conic",
      "mesh",
      "noise",
      "duotone",
      "split",
      "diagonal",
    ],
  },
  {
    id: "stickers",
    label: "Stickers",
    icon: "Sticker",
    items: [
      "fire",
      "lightning",
      "crown",
      "trophy",
      "rocket",
      "gem",
      "bomb",
      "rainbow",
    ],
  },
  {
    id: "lines",
    label: "Lines",
    icon: "Minus",
    items: [
      "solid",
      "dashed",
      "dotted",
      "wavy",
      "zigzag",
      "double",
      "thick",
      "thin",
    ],
  },
  {
    id: "frames",
    label: "Frames",
    icon: "FrameIcon",
    items: [
      "square",
      "circle",
      "rounded",
      "arch",
      "blob",
      "hexagon",
      "star",
      "diamond",
    ],
  },
  {
    id: "social",
    label: "Social Icons",
    icon: "Share2",
    items: [
      "instagram",
      "youtube",
      "tiktok",
      "twitter",
      "linkedin",
      "facebook",
      "discord",
      "twitch",
    ],
  },
  {
    id: "buttons",
    label: "Buttons",
    icon: "MousePointer",
    items: [
      "pill",
      "rounded",
      "square",
      "outline",
      "ghost",
      "neon",
      "gradient",
      "3d",
    ],
  },
  {
    id: "ui",
    label: "UI Assets",
    icon: "Layout",
    items: [
      "card",
      "badge",
      "tag",
      "progress",
      "chart",
      "table",
      "modal",
      "tooltip",
    ],
  },
  {
    id: "decorative",
    label: "Decorative",
    icon: "Sparkles",
    items: [
      "confetti",
      "dots",
      "grid",
      "halftone",
      "noise",
      "grain",
      "wave",
      "circuit",
    ],
  },
];

// ─── Stock Image Categories ──────────────────────────────────────────────────

export const STOCK_IMAGE_CATEGORIES = [
  {
    id: "nature",
    label: "Nature",
    images: [
      "https://picsum.photos/seed/nature1/400/300",
      "https://picsum.photos/seed/nature2/400/300",
      "https://picsum.photos/seed/nature3/400/300",
      "https://picsum.photos/seed/nature4/400/300",
      "https://picsum.photos/seed/nature5/400/300",
      "https://picsum.photos/seed/nature6/400/300",
    ],
  },
  {
    id: "gaming",
    label: "Gaming",
    images: [
      "https://picsum.photos/seed/gaming1/400/300",
      "https://picsum.photos/seed/gaming2/400/300",
      "https://picsum.photos/seed/gaming3/400/300",
      "https://picsum.photos/seed/gaming4/400/300",
      "https://picsum.photos/seed/gaming5/400/300",
      "https://picsum.photos/seed/gaming6/400/300",
    ],
  },
  {
    id: "technology",
    label: "Technology",
    images: [
      "https://picsum.photos/seed/tech1/400/300",
      "https://picsum.photos/seed/tech2/400/300",
      "https://picsum.photos/seed/tech3/400/300",
      "https://picsum.photos/seed/tech4/400/300",
      "https://picsum.photos/seed/tech5/400/300",
      "https://picsum.photos/seed/tech6/400/300",
    ],
  },
  {
    id: "business",
    label: "Business",
    images: [
      "https://picsum.photos/seed/biz1/400/300",
      "https://picsum.photos/seed/biz2/400/300",
      "https://picsum.photos/seed/biz3/400/300",
      "https://picsum.photos/seed/biz4/400/300",
      "https://picsum.photos/seed/biz5/400/300",
      "https://picsum.photos/seed/biz6/400/300",
    ],
  },
  {
    id: "abstract",
    label: "Abstract",
    images: [
      "https://picsum.photos/seed/abs1/400/300",
      "https://picsum.photos/seed/abs2/400/300",
      "https://picsum.photos/seed/abs3/400/300",
      "https://picsum.photos/seed/abs4/400/300",
      "https://picsum.photos/seed/abs5/400/300",
      "https://picsum.photos/seed/abs6/400/300",
    ],
  },
  {
    id: "people",
    label: "People",
    images: [
      "https://picsum.photos/seed/ppl1/400/300",
      "https://picsum.photos/seed/ppl2/400/300",
      "https://picsum.photos/seed/ppl3/400/300",
      "https://picsum.photos/seed/ppl4/400/300",
      "https://picsum.photos/seed/ppl5/400/300",
      "https://picsum.photos/seed/ppl6/400/300",
    ],
  },
  {
    id: "cars",
    label: "Cars",
    images: [
      "https://picsum.photos/seed/car1/400/300",
      "https://picsum.photos/seed/car2/400/300",
      "https://picsum.photos/seed/car3/400/300",
      "https://picsum.photos/seed/car4/400/300",
      "https://picsum.photos/seed/car5/400/300",
      "https://picsum.photos/seed/car6/400/300",
    ],
  },
  {
    id: "space",
    label: "Space",
    images: [
      "https://picsum.photos/seed/space1/400/300",
      "https://picsum.photos/seed/space2/400/300",
      "https://picsum.photos/seed/space3/400/300",
      "https://picsum.photos/seed/space4/400/300",
      "https://picsum.photos/seed/space5/400/300",
      "https://picsum.photos/seed/space6/400/300",
    ],
  },
  {
    id: "luxury",
    label: "Luxury",
    images: [
      "https://picsum.photos/seed/lux1/400/300",
      "https://picsum.photos/seed/lux2/400/300",
      "https://picsum.photos/seed/lux3/400/300",
      "https://picsum.photos/seed/lux4/400/300",
      "https://picsum.photos/seed/lux5/400/300",
      "https://picsum.photos/seed/lux6/400/300",
    ],
  },
  {
    id: "minimal",
    label: "Minimal",
    images: [
      "https://picsum.photos/seed/min1/400/300",
      "https://picsum.photos/seed/min2/400/300",
      "https://picsum.photos/seed/min3/400/300",
      "https://picsum.photos/seed/min4/400/300",
      "https://picsum.photos/seed/min5/400/300",
      "https://picsum.photos/seed/min6/400/300",
    ],
  },
];

// ─── Export Formats & Qualities ──────────────────────────────────────────────

export const EXPORT_FORMATS = [
  {
    id: "png",
    label: "PNG",
    description: "Lossless with transparency",
    icon: "Image",
  },
  {
    id: "jpg",
    label: "JPG",
    description: "Compressed, no transparency",
    icon: "FileImage",
  },
  {
    id: "webp",
    label: "WEBP",
    description: "Modern web format",
    icon: "Globe",
  },
  {
    id: "pdf",
    label: "PDF",
    description: "Print-ready document",
    icon: "FileText",
  },
  { id: "mp4", label: "MP4", description: "Animated export", icon: "Film" },
] as const;

export const EXPORT_QUALITIES = [
  {
    id: "72",
    label: "72 DPI",
    multiplier: 1,
    description: "Standard web quality",
  },
  {
    id: "150",
    label: "150 DPI",
    multiplier: 2,
    description: "High quality print",
  },
  {
    id: "300",
    label: "300 DPI",
    multiplier: 4,
    description: "Professional print",
  },
] as const;

// ─── Animation Presets ────────────────────────────────────────────────────────

export const ANIMATION_PRESETS = [
  { id: "none", label: "None", description: "No animation" },
  {
    id: "fade-in",
    label: "Fade In",
    description: "Smooth fade in from invisible",
  },
  { id: "slide-in", label: "Slide In", description: "Slide in from left" },
  { id: "scale-pop", label: "Scale Pop", description: "Scale up with bounce" },
  { id: "bounce", label: "Bounce", description: "Playful bounce entrance" },
  { id: "pulse", label: "Pulse", description: "Pulsing glow loop" },
] as const;

// ─── Blend Modes ─────────────────────────────────────────────────────────────

export const BLEND_MODES = [
  "normal",
  "multiply",
  "screen",
  "overlay",
  "darken",
  "lighten",
  "color-dodge",
  "color-burn",
  "hard-light",
  "soft-light",
  "difference",
  "exclusion",
  "hue",
  "saturation",
  "color",
  "luminosity",
] as const;

// ─── Demo Layers (for initial state) ─────────────────────────────────────────

export const DEMO_LAYER_NAMES = [
  { name: "Background", type: "rect" as const },
  { name: "Glow Accent", type: "circle" as const },
  { name: "Accent Bar", type: "rect" as const },
  { name: "Headline Text", type: "text" as const },
  { name: "Subtitle", type: "text" as const },
  { name: "CTA Button", type: "rect" as const },
  { name: "CTA Label", type: "text" as const },
  { name: "Decorative Circle", type: "circle" as const },
  { name: "Star Badge", type: "star" as const },
  { name: "Logo Image", type: "image" as const },
];

// ─── Demo Templates Catalog ──────────────────────────────────────────────────

export const DEMO_TEMPLATE_CATEGORIES = [
  {
    id: "youtube",
    label: "YouTube Thumbnails",
    templates: [
      {
        id: "yt-bold",
        label: "YouTube Bold",
        thumbnail: "https://picsum.photos/seed/yt1/320/180",
      },
      {
        id: "yt-neon",
        label: "YouTube Neon",
        thumbnail: "https://picsum.photos/seed/yt2/320/180",
      },
    ],
  },
  {
    id: "instagram",
    label: "Instagram Posts",
    templates: [
      {
        id: "ig-brand",
        label: "Instagram Brand",
        thumbnail: "https://picsum.photos/seed/ig1/320/320",
      },
      {
        id: "ig-product",
        label: "Product Showcase",
        thumbnail: "https://picsum.photos/seed/ig2/320/320",
      },
    ],
  },
  {
    id: "tiktok",
    label: "TikTok Covers",
    templates: [
      {
        id: "tiktok-hook",
        label: "Attention Hook",
        thumbnail: "https://picsum.photos/seed/tt1/180/320",
      },
      {
        id: "tiktok-story",
        label: "TikTok Story",
        thumbnail: "https://picsum.photos/seed/tt2/180/320",
      },
    ],
  },
  {
    id: "posters",
    label: "Posters",
    templates: [
      {
        id: "event-poster",
        label: "Event Poster",
        thumbnail: "https://picsum.photos/seed/poster1/320/400",
      },
      {
        id: "concert-poster",
        label: "Concert Poster",
        thumbnail: "https://picsum.photos/seed/poster2/320/400",
      },
    ],
  },
  {
    id: "ads",
    label: "Business Ads",
    templates: [
      {
        id: "blog-feature",
        label: "Blog Feature",
        thumbnail: "https://picsum.photos/seed/ad1/320/168",
      },
      {
        id: "linkedin-pro",
        label: "LinkedIn Banner",
        thumbnail: "https://picsum.photos/seed/ad2/320/168",
      },
    ],
  },
  {
    id: "gaming",
    label: "Gaming Thumbnails",
    templates: [
      {
        id: "game-thumb1",
        label: "Epic Gaming",
        thumbnail: "https://picsum.photos/seed/game1/320/180",
      },
      {
        id: "game-thumb2",
        label: "Neon Gamer",
        thumbnail: "https://picsum.photos/seed/game2/320/180",
      },
    ],
  },
  {
    id: "podcasts",
    label: "Podcasts",
    templates: [
      {
        id: "podcast1",
        label: "Podcast Cover",
        thumbnail: "https://picsum.photos/seed/pod1/320/320",
      },
      {
        id: "podcast2",
        label: "Episode Card",
        thumbnail: "https://picsum.photos/seed/pod2/320/320",
      },
    ],
  },
  {
    id: "courses",
    label: "Courses",
    templates: [
      {
        id: "course-banner",
        label: "Course Banner",
        thumbnail: "https://picsum.photos/seed/course1/320/180",
      },
      {
        id: "course-cert",
        label: "Certificate",
        thumbnail: "https://picsum.photos/seed/course2/320/180",
      },
    ],
  },
  {
    id: "ai-content",
    label: "AI Content",
    templates: [
      {
        id: "ai-card",
        label: "AI Insight Card",
        thumbnail: "https://picsum.photos/seed/ai1/320/320",
      },
      {
        id: "ai-promo",
        label: "AI Tool Promo",
        thumbnail: "https://picsum.photos/seed/ai2/320/180",
      },
    ],
  },
  {
    id: "cinematic",
    label: "Cinematic",
    templates: [
      {
        id: "cinema1",
        label: "Film Poster",
        thumbnail: "https://picsum.photos/seed/cine1/320/480",
      },
      {
        id: "cinema2",
        label: "Scene Teaser",
        thumbnail: "https://picsum.photos/seed/cine2/320/180",
      },
    ],
  },
];

// ─── AI Design Suggestions ────────────────────────────────────────────────────

export const AI_SUGGESTIONS = [
  {
    id: "magic-resize",
    label: "Magic Resize",
    description: "Instantly reformat for any platform",
    icon: "Wand2",
  },
  {
    id: "color-match",
    label: "Color Match",
    description: "Auto-extract palette from uploaded image",
    icon: "Pipette",
  },
  {
    id: "auto-layout",
    label: "Auto Layout",
    description: "Intelligently align and distribute elements",
    icon: "AlignCenter",
  },
  {
    id: "ai-enhance",
    label: "AI Enhance",
    description: "Upscale and sharpen images with AI",
    icon: "Sparkles",
  },
  {
    id: "bg-remove",
    label: "Remove Background",
    description: "Instantly remove image backgrounds",
    icon: "Eraser",
  },
];

// ─── Workspace Presets ────────────────────────────────────────────────────────

export const WORKSPACE_PRESETS: WorkspacePreset[] = [
  {
    id: "default",
    name: "Default",
    canvasWidth: 1280,
    canvasHeight: 720,
    zoom: 0.6,
    gridEnabled: false,
    snapEnabled: true,
  },
  {
    id: "mobile",
    name: "Mobile First",
    canvasWidth: 1080,
    canvasHeight: 1920,
    zoom: 0.35,
    gridEnabled: true,
    snapEnabled: true,
  },
  {
    id: "square",
    name: "Square",
    canvasWidth: 1080,
    canvasHeight: 1080,
    zoom: 0.5,
    gridEnabled: false,
    snapEnabled: true,
  },
  {
    id: "print",
    name: "Print A4",
    canvasWidth: 2480,
    canvasHeight: 3508,
    zoom: 0.2,
    gridEnabled: true,
    snapEnabled: true,
  },
];

// ─── Recent Projects (Demo) ───────────────────────────────────────────────────

export const DEMO_RECENT_PROJECTS: RecentProject[] = [
  {
    id: "proj-1",
    name: "YouTube Thumbnail — EP 42",
    thumbnail: "https://picsum.photos/seed/proj1/320/180",
    lastModified: Date.now() - 1000 * 60 * 30,
    canvasSize: { width: 1280, height: 720 },
    category: "Video",
  },
  {
    id: "proj-2",
    name: "Instagram Collab Drop",
    thumbnail: "https://picsum.photos/seed/proj2/320/320",
    lastModified: Date.now() - 1000 * 60 * 60 * 3,
    canvasSize: { width: 1080, height: 1080 },
    category: "Social",
  },
  {
    id: "proj-3",
    name: "Course Banner — Masterclass",
    thumbnail: "https://picsum.photos/seed/proj3/320/180",
    lastModified: Date.now() - 1000 * 60 * 60 * 24,
    canvasSize: { width: 1280, height: 720 },
    category: "Education",
  },
  {
    id: "proj-4",
    name: "Elysian Brand Kit 2026",
    thumbnail: "https://picsum.photos/seed/proj4/320/180",
    lastModified: Date.now() - 1000 * 60 * 60 * 48,
    canvasSize: { width: 1500, height: 500 },
    category: "Brand",
  },
  {
    id: "proj-5",
    name: "TikTok Series — Design Tips",
    thumbnail: "https://picsum.photos/seed/proj5/180/320",
    lastModified: Date.now() - 1000 * 60 * 60 * 72,
    canvasSize: { width: 1080, height: 1920 },
    category: "Video",
  },
];

export const QUICK_COLORS = [
  "#ffffff",
  "#000000",
  "#101820",
  "#0047ab",
  "#50c878",
  "#00ff00",
  "#ff4444",
  "#f59e0b",
  "#a78bfa",
  "#f472b6",
  "#06b6d4",
  "#ef4444",
];

const mkEl = <T extends TemplateElement>(e: T): TemplateElement => e;

export const TEMPLATES: Template[] = [
  {
    id: "yt-clean",
    label: "YouTube Bold",
    category: "Video",
    preset: CANVAS_PRESETS[0],
    elements: [
      mkEl({
        type: "rect",
        name: "Background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        fillColor: "#101820",
        borderColor: "#101820",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "rect",
        name: "Accent Bar",
        x: 40,
        y: 40,
        width: 8,
        height: 640,
        fillColor: "#50c878",
        borderColor: "#50c878",
        borderWidth: 0,
        borderRadius: 4,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "text",
        name: "Title",
        x: 80,
        y: 200,
        width: 700,
        height: 100,
        content: "EPIC TITLE HERE",
        fontSize: 96,
        color: "#ffffff",
        fontFamily: "Impact",
        bold: false,
        italic: false,
        underline: false,
        align: "left" as const,
        letterSpacing: 0,
        lineHeight: 1.2,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: true,
      }),
      mkEl({
        type: "text",
        name: "Subtitle",
        x: 80,
        y: 340,
        width: 700,
        height: 50,
        content: "Your subtitle goes here",
        fontSize: 40,
        color: "#50c878",
        fontFamily: "Plus Jakarta Sans",
        bold: false,
        italic: false,
        underline: false,
        align: "left" as const,
        letterSpacing: 0,
        lineHeight: 1.4,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "rect",
        name: "CTA Button",
        x: 80,
        y: 440,
        width: 300,
        height: 70,
        fillColor: "#0047ab",
        borderColor: "#0047ab",
        borderWidth: 0,
        borderRadius: 8,
        opacity: 0.9,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: true,
      }),
      mkEl({
        type: "text",
        name: "CTA Text",
        x: 110,
        y: 490,
        width: 240,
        height: 40,
        content: "WATCH NOW",
        fontSize: 32,
        color: "#ffffff",
        fontFamily: "Impact",
        bold: false,
        italic: false,
        underline: false,
        align: "center" as const,
        letterSpacing: 2,
        lineHeight: 1,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
    ],
  },
  {
    id: "ig-brand",
    label: "Instagram Brand",
    category: "Social",
    preset: CANVAS_PRESETS[1],
    elements: [
      mkEl({
        type: "rect",
        name: "Background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        fillColor: "#101820",
        borderColor: "#101820",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "circle",
        name: "Glow Circle",
        x: 240,
        y: 240,
        width: 600,
        height: 600,
        fillColor: "#50c878",
        borderColor: "#50c878",
        borderWidth: 0,
        opacity: 0.06,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "text",
        name: "Brand Name",
        x: 120,
        y: 380,
        width: 840,
        height: 120,
        content: "YOUR BRAND",
        fontSize: 90,
        color: "#ffffff",
        fontFamily: "Impact",
        bold: false,
        italic: false,
        underline: false,
        align: "center" as const,
        letterSpacing: 4,
        lineHeight: 1.2,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: true,
      }),
      mkEl({
        type: "text",
        name: "Tagline",
        x: 160,
        y: 530,
        width: 760,
        height: 60,
        content: "A tagline that resonates",
        fontSize: 44,
        color: "#50c878",
        fontFamily: "Plus Jakarta Sans",
        bold: false,
        italic: false,
        underline: false,
        align: "center" as const,
        letterSpacing: 0,
        lineHeight: 1.4,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "rect",
        name: "CTA Button",
        x: 320,
        y: 660,
        width: 440,
        height: 80,
        fillColor: "#0047ab",
        borderColor: "#0047ab",
        borderWidth: 0,
        borderRadius: 40,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: true,
      }),
      mkEl({
        type: "text",
        name: "CTA Text",
        x: 360,
        y: 707,
        width: 360,
        height: 46,
        content: "LEARN MORE",
        fontSize: 36,
        color: "#ffffff",
        fontFamily: "Impact",
        bold: false,
        italic: false,
        underline: false,
        align: "center" as const,
        letterSpacing: 3,
        lineHeight: 1,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
    ],
  },
  {
    id: "twitter-banner",
    label: "Twitter Banner",
    category: "Social",
    preset: CANVAS_PRESETS[2],
    elements: [
      mkEl({
        type: "rect",
        name: "Background",
        x: 0,
        y: 0,
        width: 1500,
        height: 500,
        fillColor: "#101820",
        borderColor: "#101820",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "rect",
        name: "Top Bar",
        x: 0,
        y: 0,
        width: 1500,
        height: 4,
        fillColor: "#50c878",
        borderColor: "#50c878",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "text",
        name: "Brand",
        x: 80,
        y: 180,
        width: 900,
        height: 120,
        content: "Elysian Labs",
        fontSize: 100,
        color: "#ffffff",
        fontFamily: "Plus Jakarta Sans",
        bold: true,
        italic: false,
        underline: false,
        align: "left" as const,
        letterSpacing: -2,
        lineHeight: 1.1,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: true,
      }),
      mkEl({
        type: "text",
        name: "Tagline",
        x: 80,
        y: 320,
        width: 800,
        height: 60,
        content: "Creative Studio",
        fontSize: 46,
        color: "#50c878",
        fontFamily: "Plus Jakarta Sans",
        bold: false,
        italic: false,
        underline: false,
        align: "left" as const,
        letterSpacing: 0,
        lineHeight: 1.4,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "rect",
        name: "Bottom Bar",
        x: 0,
        y: 496,
        width: 1500,
        height: 4,
        fillColor: "#0047ab",
        borderColor: "#0047ab",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
    ],
  },
  {
    id: "linkedin-pro",
    label: "LinkedIn Banner",
    category: "Social",
    preset: CANVAS_PRESETS[4],
    elements: [
      mkEl({
        type: "rect",
        name: "Background",
        x: 0,
        y: 0,
        width: 1200,
        height: 628,
        fillColor: "#101820",
        borderColor: "#101820",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "rect",
        name: "Side Accent",
        x: 0,
        y: 0,
        width: 400,
        height: 628,
        fillColor: "#0047ab",
        borderColor: "#0047ab",
        borderWidth: 0,
        borderRadius: 0,
        opacity: 0.4,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "text",
        name: "Name",
        x: 80,
        y: 200,
        width: 700,
        height: 80,
        content: "Professional Name",
        fontSize: 72,
        color: "#ffffff",
        fontFamily: "Plus Jakarta Sans",
        bold: true,
        italic: false,
        underline: false,
        align: "left" as const,
        letterSpacing: -1,
        lineHeight: 1.2,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
      mkEl({
        type: "text",
        name: "Title",
        x: 80,
        y: 310,
        width: 700,
        height: 50,
        content: "Role / Company",
        fontSize: 40,
        color: "#50c878",
        fontFamily: "Plus Jakarta Sans",
        bold: false,
        italic: false,
        underline: false,
        align: "left" as const,
        letterSpacing: 0,
        lineHeight: 1.4,
        opacity: 1,
        rotation: 0,
        locked: false,
        visible: true,
        shadow: false,
      }),
    ],
  },
];

// The helper below is exported so other modules can compose new template elements
export { mkEl };

// ─── Extra Templates: Product Showcase, Course Banner, Event Poster, Portfolio Header, Blog Feature, TikTok Story ───

const productShowcaseElements: TemplateElement[] = [
  mkEl({
    type: "rect",
    name: "Background",
    x: 0,
    y: 0,
    width: 1080,
    height: 1080,
    fillColor: "#0a0f1a",
    borderColor: "#0a0f1a",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Gradient Overlay",
    x: 0,
    y: 0,
    width: 1080,
    height: 1080,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0.12,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#0047ab", "#50c878"],
      angle: 135,
    },
  }),
  mkEl({
    type: "circle",
    name: "Glow Accent",
    x: 340,
    y: 200,
    width: 400,
    height: 400,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    opacity: 0.07,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Product Frame",
    x: 290,
    y: 180,
    width: 500,
    height: 420,
    fillColor: "#1a2744",
    borderColor: "#0047ab",
    borderWidth: 2,
    borderRadius: 24,
    opacity: 0.85,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "rect",
    name: "Badge",
    x: 80,
    y: 80,
    width: 200,
    height: 52,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 26,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "Badge Label",
    x: 90,
    y: 97,
    width: 180,
    height: 36,
    content: "\u2726 NEW ARRIVAL",
    fontSize: 20,
    color: "#0a0f1a",
    fontFamily: "Inter",
    bold: true,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 1,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Product Name",
    x: 80,
    y: 650,
    width: 920,
    height: 90,
    content: "Elysian Pro Creator Kit",
    fontSize: 70,
    color: "#ffffff",
    fontFamily: "Plus Jakarta Sans",
    bold: true,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: -2,
    lineHeight: 1.1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "Tagline",
    x: 80,
    y: 760,
    width: 800,
    height: 50,
    content: "Design. Create. Inspire.",
    fontSize: 36,
    color: "#50c878",
    fontFamily: "Plus Jakarta Sans",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Feature 1",
    x: 80,
    y: 840,
    width: 500,
    height: 36,
    content: "\u2713  Professional-grade tools",
    fontSize: 22,
    color: "#a0b4c8",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Feature 2",
    x: 80,
    y: 882,
    width: 500,
    height: 36,
    content: "\u2713  100+ premium templates",
    fontSize: 22,
    color: "#a0b4c8",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "CTA Button",
    x: 80,
    y: 940,
    width: 260,
    height: 64,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 32,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "CTA Text",
    x: 100,
    y: 962,
    width: 220,
    height: 36,
    content: "Get Started Free",
    fontSize: 24,
    color: "#ffffff",
    fontFamily: "Inter",
    bold: true,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 0,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
];

const courseBannerElements: TemplateElement[] = [
  mkEl({
    type: "rect",
    name: "Background",
    x: 0,
    y: 0,
    width: 1280,
    height: 720,
    fillColor: "#080c14",
    borderColor: "#080c14",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Gradient BG",
    x: 0,
    y: 0,
    width: 1280,
    height: 720,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0.1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#0047ab", "#50c878"],
      angle: 45,
    },
  }),
  mkEl({
    type: "rect",
    name: "Left Accent",
    x: 0,
    y: 0,
    width: 6,
    height: 720,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "circle",
    name: "Glow Orb Left",
    x: -80,
    y: 200,
    width: 400,
    height: 400,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    opacity: 0.18,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "circle",
    name: "Glow Orb Right",
    x: 980,
    y: 100,
    width: 500,
    height: 500,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    opacity: 0.08,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "FREE Badge",
    x: 80,
    y: 80,
    width: 180,
    height: 52,
    fillColor: "#00ff00",
    borderColor: "#00ff00",
    borderWidth: 0,
    borderRadius: 8,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "Badge Text",
    x: 90,
    y: 97,
    width: 160,
    height: 36,
    content: "FREE COURSE",
    fontSize: 24,
    color: "#0a0f1a",
    fontFamily: "Inter",
    bold: true,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 2,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Course Title",
    x: 80,
    y: 200,
    width: 900,
    height: 200,
    content: "Thumbnail Design Masterclass",
    fontSize: 90,
    color: "#ffffff",
    fontFamily: "Impact",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: -1,
    lineHeight: 1.1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "Instructor",
    x: 80,
    y: 420,
    width: 500,
    height: 50,
    content: "Taught by Elysian AI",
    fontSize: 32,
    color: "#50c878",
    fontFamily: "Plus Jakarta Sans",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Lesson Count",
    x: 80,
    y: 468,
    width: 500,
    height: 36,
    content: "15 Lessons  \u00b7  Beginner Friendly",
    fontSize: 24,
    color: "#7a8ba0",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "CTA Button",
    x: 80,
    y: 540,
    width: 320,
    height: 70,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 12,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "CTA Text",
    x: 100,
    y: 562,
    width: 280,
    height: 42,
    content: "ENROLL NOW \u2014 FREE",
    fontSize: 28,
    color: "#ffffff",
    fontFamily: "Impact",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 2,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
];

const eventPosterElements: TemplateElement[] = [
  mkEl({
    type: "rect",
    name: "Background",
    x: 0,
    y: 0,
    width: 1080,
    height: 1350,
    fillColor: "#080c14",
    borderColor: "#080c14",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#0a0f1a", "#1a0a2e"],
      angle: 180,
    },
  }),
  mkEl({
    type: "circle",
    name: "Glow Top",
    x: 140,
    y: -100,
    width: 800,
    height: 800,
    fillColor: "#6c5ce7",
    borderColor: "#6c5ce7",
    borderWidth: 0,
    opacity: 0.12,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "circle",
    name: "Glow Bottom",
    x: 300,
    y: 900,
    width: 600,
    height: 600,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    opacity: 0.1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Top Accent",
    x: 0,
    y: 0,
    width: 1080,
    height: 6,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Pre-Title",
    x: 80,
    y: 120,
    width: 920,
    height: 50,
    content: "\u2726 ELYSIAN LABS PRESENTS \u2726",
    fontSize: 26,
    color: "#50c878",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 4,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Event Name",
    x: 80,
    y: 220,
    width: 920,
    height: 300,
    content: "Creative Summit 2026",
    fontSize: 120,
    color: "#ffffff",
    fontFamily: "Impact",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 0,
    lineHeight: 1.05,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "rect",
    name: "Divider",
    x: 340,
    y: 560,
    width: 400,
    height: 3,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 2,
    opacity: 0.6,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Date",
    x: 80,
    y: 600,
    width: 920,
    height: 60,
    content: "JUNE 14\u201315, 2026",
    fontSize: 40,
    color: "#ffffff",
    fontFamily: "Plus Jakarta Sans",
    bold: true,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 3,
    lineHeight: 1.2,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Venue",
    x: 80,
    y: 680,
    width: 920,
    height: 50,
    content: "Virtual \u2014 Elysian Online Campus",
    fontSize: 30,
    color: "#7a8ba0",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 1,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "CTA Button",
    x: 240,
    y: 820,
    width: 600,
    height: 80,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 40,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "CTA Text",
    x: 260,
    y: 844,
    width: 560,
    height: 46,
    content: "REGISTER NOW \u2014 FREE",
    fontSize: 32,
    color: "#ffffff",
    fontFamily: "Impact",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 3,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
];

const portfolioHeaderElements: TemplateElement[] = [
  mkEl({
    type: "rect",
    name: "Background",
    x: 0,
    y: 0,
    width: 1500,
    height: 500,
    fillColor: "#080c14",
    borderColor: "#080c14",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Left Panel",
    x: 0,
    y: 0,
    width: 480,
    height: 500,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0.15,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#0047ab", "#101820"],
      angle: 90,
    },
  }),
  mkEl({
    type: "rect",
    name: "Top Line",
    x: 0,
    y: 0,
    width: 1500,
    height: 4,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Bottom Line",
    x: 0,
    y: 496,
    width: 1500,
    height: 4,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Accent Shape",
    x: 1260,
    y: 60,
    width: 180,
    height: 180,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 90,
    opacity: 0.08,
    rotation: 45,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Accent Shape 2",
    x: 1350,
    y: 260,
    width: 120,
    height: 120,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 60,
    opacity: 0.1,
    rotation: 30,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Name",
    x: 60,
    y: 140,
    width: 800,
    height: 120,
    content: "Aneeshwar R.",
    fontSize: 88,
    color: "#ffffff",
    fontFamily: "Plus Jakarta Sans",
    bold: true,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: -2,
    lineHeight: 1.1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Role",
    x: 60,
    y: 290,
    width: 600,
    height: 60,
    content: "Creative Director & Founder",
    fontSize: 38,
    color: "#50c878",
    fontFamily: "Plus Jakarta Sans",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Website",
    x: 60,
    y: 380,
    width: 500,
    height: 40,
    content: "elysianlabs.io",
    fontSize: 26,
    color: "#7a8ba0",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
];

const blogFeatureElements: TemplateElement[] = [
  mkEl({
    type: "rect",
    name: "Background",
    x: 0,
    y: 0,
    width: 1200,
    height: 628,
    fillColor: "#0a0f1a",
    borderColor: "#0a0f1a",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#080c14", "#0d1a2e"],
      angle: 135,
    },
  }),
  mkEl({
    type: "rect",
    name: "Top Accent Bar",
    x: 0,
    y: 0,
    width: 1200,
    height: 5,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Bottom Accent",
    x: 0,
    y: 580,
    width: 1200,
    height: 48,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0.2,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#0047ab", "#50c878"],
      angle: 90,
    },
  }),
  mkEl({
    type: "rect",
    name: "Category Badge",
    x: 60,
    y: 60,
    width: 180,
    height: 44,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 8,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Category",
    x: 70,
    y: 74,
    width: 160,
    height: 30,
    content: "DESIGN TIPS",
    fontSize: 20,
    color: "#ffffff",
    fontFamily: "Inter",
    bold: true,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 2,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Article Title",
    x: 60,
    y: 140,
    width: 900,
    height: 220,
    content: "10 Pro Techniques to Level Up Your Thumbnails",
    fontSize: 72,
    color: "#ffffff",
    fontFamily: "Plus Jakarta Sans",
    bold: true,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: -1,
    lineHeight: 1.1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Author",
    x: 60,
    y: 390,
    width: 500,
    height: 40,
    content: "By Elysian AI",
    fontSize: 28,
    color: "#50c878",
    fontFamily: "Plus Jakarta Sans",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Date",
    x: 60,
    y: 438,
    width: 400,
    height: 36,
    content: "May 7, 2026  \u00b7  6 min read",
    fontSize: 22,
    color: "#7a8ba0",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "left" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
];

const tiktokStoryElements: TemplateElement[] = [
  mkEl({
    type: "rect",
    name: "Background",
    x: 0,
    y: 0,
    width: 1080,
    height: 1920,
    fillColor: "#080c14",
    borderColor: "#080c14",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
    gradientFill: {
      type: "gradient" as const,
      colors: ["#0a0f1a", "#1a0a2e"],
      angle: 180,
    },
  }),
  mkEl({
    type: "circle",
    name: "Glow Top Left",
    x: -200,
    y: -200,
    width: 800,
    height: 800,
    fillColor: "#6c5ce7",
    borderColor: "#6c5ce7",
    borderWidth: 0,
    opacity: 0.2,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "circle",
    name: "Glow Bottom Right",
    x: 480,
    y: 1320,
    width: 700,
    height: 700,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    opacity: 0.1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Color Block Left",
    x: 0,
    y: 600,
    width: 200,
    height: 720,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0.3,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "Color Block Right",
    x: 880,
    y: 400,
    width: 200,
    height: 600,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 0,
    opacity: 0.2,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Attention Hook",
    x: 80,
    y: 300,
    width: 920,
    height: 300,
    content: "Want more views?",
    fontSize: 130,
    color: "#ffffff",
    fontFamily: "Impact",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 0,
    lineHeight: 1.05,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "rect",
    name: "Divider",
    x: 200,
    y: 660,
    width: 680,
    height: 4,
    fillColor: "#50c878",
    borderColor: "#50c878",
    borderWidth: 0,
    borderRadius: 2,
    opacity: 0.7,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "Sub Caption",
    x: 80,
    y: 720,
    width: 920,
    height: 160,
    content: "Use these 5 thumbnail tips from Elysian AI",
    fontSize: 64,
    color: "#50c878",
    fontFamily: "Plus Jakarta Sans",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 0,
    lineHeight: 1.2,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "text",
    name: "CTA Arrow",
    x: 80,
    y: 1000,
    width: 920,
    height: 80,
    content: "\ud83d\udc47 Tap to learn more",
    fontSize: 50,
    color: "#ffffff",
    fontFamily: "Inter",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 0,
    lineHeight: 1.4,
    opacity: 0.85,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
  mkEl({
    type: "rect",
    name: "CTA Button",
    x: 190,
    y: 1600,
    width: 700,
    height: 90,
    fillColor: "#0047ab",
    borderColor: "#0047ab",
    borderWidth: 0,
    borderRadius: 45,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: true,
  }),
  mkEl({
    type: "text",
    name: "CTA Text",
    x: 200,
    y: 1624,
    width: 680,
    height: 54,
    content: "START CREATING FREE",
    fontSize: 36,
    color: "#ffffff",
    fontFamily: "Impact",
    bold: false,
    italic: false,
    underline: false,
    align: "center" as const,
    letterSpacing: 3,
    lineHeight: 1,
    opacity: 1,
    rotation: 0,
    locked: false,
    visible: true,
    shadow: false,
  }),
];

TEMPLATES.push(
  {
    id: "product-showcase",
    label: "Product Showcase",
    category: "Social",
    preset: CANVAS_PRESETS[1],
    elements: productShowcaseElements,
  },
  {
    id: "course-banner",
    label: "Course Banner",
    category: "Education",
    preset: CANVAS_PRESETS[0],
    elements: courseBannerElements,
  },
  {
    id: "event-poster",
    label: "Event Poster",
    category: "Events",
    preset: {
      label: "Event Poster",
      category: "Events",
      width: 1080,
      height: 1350,
      icon: "\ud83c\udfad",
    },
    elements: eventPosterElements,
  },
  {
    id: "portfolio-header",
    label: "Portfolio Header",
    category: "Social",
    preset: CANVAS_PRESETS[2],
    elements: portfolioHeaderElements,
  },
  {
    id: "blog-feature",
    label: "Blog Feature",
    category: "Content",
    preset: CANVAS_PRESETS[4],
    elements: blogFeatureElements,
  },
  {
    id: "tiktok-story",
    label: "TikTok Story",
    category: "Video",
    preset: CANVAS_PRESETS[3],
    elements: tiktokStoryElements,
  },
);
